defaults:
  - autoencoder: stable_vae
  - backbone: mm_dit
  - _self_

# 全部都改到1024维度
content_dim: 1024
noise_scheduler_name: "stabilityai/stable-diffusion-2-1"
snr_gamma: 5.0
cfg_drop_ratio: 0.2

backbone:
  ta_context_dim: 128

# 改为单任务
_target_: models.diffusion.SingleTaskCrossAttentionAudioDiffusion
content_encoder:
  _target_: models.content_encoder.content_encoder.ContentEncoder
  embed_dim: ${..content_dim}
  text_encoder:
    _target_: models.content_encoder.llm_encoder.Qwen2AudioEmbedder
    model_path: /mnt/petrelfs/taoye/workspace/model/qwen25audio
    embed_dim: ${...content_dim}
    max_length: 320
  audio_encoder:
    _target_: models.autoencoder.waveform.stable_vae.StableVAEProjectorWrapper
    vae_dim: ${...autoencoder.latent_dim}
    embed_dim: 128