defaults:
  - basic
  - data@data_dict: example
  - _self_

test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ${data_dict.test_data_list.0}
  batch_size: 1 # per device batch size
  shuffle: True
  num_workers: 4
  collate_fn:
    _target_: data_module.collate_function.PaddingCollate
    pad_keys: ["instruction"]

wav_dir: inference
output_subdir: example
noise_scheduler:
  type: DDIMScheduler
  name: stabilityai/stable-diffusion-2-1

infer_args:
  num_steps: 50
  guidance_scale: 5.0
  guidance_rescale: 0.5
  use_gt_duration: false
  mask_time_aligned_content: false